# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobHistory',
            new_name='JobHistoryModel',
        ),
        migrations.RenameModel(
            old_name='JobHistorySync',
            new_name='JobHistorySyncModel',
        ),
    ]
